In [9]:

import pandas as pd
from sklearn.datasets import load_california_housing

#sklearn dataset (Bunch) → DIAB.feature_names ,,,when bunch object is created its just ft_name=obj_name.feature_names
#Pandas DataFrame → DataFrameName.columns.tolist()  ,,,when dataframe is created its just df_name.columns.tolist()
#above mentioned 2 lines r to get column names of the dataset


SyntaxError: invalid syntax (3862880881.py, line 1)

In [6]:
ca=load_california_housing()

NameError: name 'load_california_housing' is not defined

In [10]:
df=pd.DataFrame(ca.data,columns=ca.feature_names)


In [13]:
print(ca.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


In [25]:
print(df.head())
print("---------------------------------info below-------------------------------------------------------------------------")
print(df.info())
print("-----------------------------------tail below-----------------------------------------------------------------------")
print(df.tail())
print("-------------------------------------description below-----------------------------------------------------------------")
print(df.describe())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  
---------------------------------info below-------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 

In [15]:
print(ca.data)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]


In [18]:
print(ca.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB
None


In [34]:
db_df=pd.read_csv("C:\\Users\\USER\\Downloads\\diabetes.csv")  #bringing csv file to dataframe

In [78]:
db_df.head()
db_df.shape

(768, 9)

In [36]:
type(db_df)

pandas.core.frame.DataFrame

In [37]:
db_df.to_csv("diab.csv")  #db_df(db_df dataframe ) is moved back to csv file

In [32]:
d=pd.read_csv("diab.csv")   #re-assuring whether diab.csv is created or not from prev
d.head()

Unnamed: 0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0           0            6      148             72             35        0   
1           1            1       85             66             29        0   
2           2            8      183             64              0        0   
3           3            1       89             66             23       94   
4           4            0      137             40             35      168   

    BMI  DiabetesPedigreeFunction  Age  Outcome  
0  33.6                     0.627   50        1  
1  26.6                     0.351   31        0  
2  23.3                     0.672   32        1  
3  28.1                     0.167   21        0  
4  43.1                     2.288   33        1

In [59]:
db_df.head()
db_df.shape

(768, 9)

In [48]:
db_df.min()


Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

In [49]:
db_df.max()


Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

In [50]:
db_df.mean()


Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [51]:
db_df.std()


Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

In [52]:
db_df.median()

Pregnancies                   3.0000
Glucose                     117.0000
BloodPressure                72.0000
SkinThickness                23.0000
Insulin                      30.5000
BMI                          32.0000
DiabetesPedigreeFunction      0.3725
Age                          29.0000
Outcome                       0.0000
dtype: float64

In [54]:
db_df.sum()

Pregnancies                  2953.000
Glucose                     92847.000
BloodPressure               53073.000
SkinThickness               15772.000
Insulin                     61286.000
BMI                         24570.300
DiabetesPedigreeFunction      362.401
Age                         25529.000
Outcome                       268.000
dtype: float64

In [55]:
db_df.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [56]:
db_df.shape

(768, 9)

In [57]:
db_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [74]:
# Drop row(s) by index in Pandas

db_df = db_df.drop(index=2,axis=0) 
db_df.head()
db_df.shape
# drop row with index 0
# db_df = db_df.drop(0, axis=0)      # same thing (explicit axis)
# db_df = db_df.drop(index=0)        # same thing (clearer!)
# db_df = db_df.drop([0, 2], axis=0) # drop multiple rows


(766, 9)

In [89]:
db_df=pd.read_csv("C:\\Users\\USER\\Downloads\\diabetes.csv")
db_df.shape

(768, 9)

In [97]:
db_df = db_df.drop('Pregnancies', axis=1, errors='ignore')
db_df.head()


BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  \
0             72             35        0  33.6                     0.627   50   
1             66             29        0  26.6                     0.351   31   
2             64              0        0  23.3                     0.672   32   
3             66             23       94  28.1                     0.167   21   
4             40             35      168  43.1                     2.288   33   

   Outcome  
0        1  
1        0  
2        1  
3        0  
4        1

In [96]:
db_df = db_df.drop('Glucose', axis=1, errors='ignore')
db_df.head()


Pregnancies  BloodPressure  SkinThickness  Insulin   BMI  \
0            6             72             35        0  33.6   
1            1             66             29        0  26.6   
2            8             64              0        0  23.3   
3            1             66             23       94  28.1   
4            0             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [99]:
db_df.columns.tolist()

['BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Outcome']

In [22]:
import numpy as np
a=np.eye(3,4)
print(a)
print(a.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
(3, 4)


In [23]:
print(a.reshape(4,3))  #rehape is not yet assigned for a its just printing 4,3 matrix 
print(a.shape)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]]
(3, 4)


In [24]:
a=a.reshape(4,3)      #if this was just written as print(a.reshape(4,3)) 
#but it will still print 3,4 bcz a was still 3,4 it reshape was not assigned to a
print(a)
print(a.shape)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]]
(4, 3)


In [19]:
a=a.ravel()   
print(a)
print(a.shape)

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
(12,)
